### ISSUE TITLE
[feature] add a "none" option

### ISSUE THREAD

**Issue by t0pd4wn** [t0pd4wn/loco.sh#6]
A `none` option should be implemented to control loco behavior from the profile, notably to limit prompts. 

- [ ]  the `-N` option could remove all prompts
- [ ] a yaml `none` value could limit prompts to specific steps

```yaml
style: none
packages: none
...
```
